apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhc2V0cmFpbmVyLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJhc2V0cmFpbmVyIiwicGFzc3dvcmQiOiJNeXBZRnhsOE42T21vOFpDak5zbGs4SGlwY1drSHptSk56a1pOL2xPNy8rQUNSQ21wdExrIiwiZW1haWwiOiJqYXNvbkBpbm5vdmF0aW9uaW5zb2Z0d2FyZS5jb20iLCJhdXRoIjoiWVhObGRISmhhVzVsY2pwTmVYQlpSbmhzT0U0MlQyMXZPRnBEYWs1emJHczRTR2x3WTFkclNIcHRTazU2YTFwT0wyeFBOeThyUVVOU1EyMXdkRXhyIn19fQ== 
kind: Secret
metadata:
  creationTimestamp: "2024-09-16T11:02:19Z"
  name: acr-secret
  namespace: default
  resourceVersion: "34773"
  uid: 66dd8a4d-c7f4-429e-9803-fb24098e8c63
type: kubernetes.io/dockerconfigjson